# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20160415_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
